# Generated by Django 3.2.25 on 2024-09-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hvc44',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvfjd', models.BigIntegerField()),
                ('tryed', models.BigIntegerField()),
            ],
        ),
    ]
